name: Expo Publish on Staging
on:
  push:
    branches:
      - develop
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 6.x
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
      - run: yarn
      - run: expo publish --release-channel staging